import type { ImportLimits } from '../../types/regflow'

interface Props {
  connected: boolean | null
  limits: ImportLimits | null
  onStart: () => void
}

function formatMegabytes(bytes: number): string {
  return `${Math.round(bytes / 1024 / 1024)} MB`
}

export function HelpStatusPage({ connected, limits, onStart }: Props) {
  return (
    <div className="platform-page">
      <section className="page-hero page-hero--compact">
        <p className="eyebrow">Help &amp; status</p>
        <h1>Know what happens at every step.</h1>
        <p>RegBridge keeps source inspection, mapping, findings, and generation explicit. Use this page to understand the current local platform and its boundaries.</p>
      </section>
      <section className="status-banner">
        <span className={`status-dot status-dot--${connected === null ? 'checking' : connected ? 'connected' : 'unavailable'}`} />
        <div><strong>{connected === null ? 'Checking platform connection' : connected ? 'Local API connected' : 'Local API unavailable'}</strong><span>{connected ? 'RegPacks and workflow services are reachable.' : 'Run Docker Compose and refresh this page.'}</span></div>
      </section>
      <div className="help-layout">
        <section className="help-card"><p className="eyebrow">RegFlow guide</p><h2>From source to output</h2><ol className="help-steps"><li><strong>Select a RegPack and version.</strong><span>The version controls schemas, sections, rules, reconciliation, and output.</span></li><li><strong>Upload once and inspect.</strong><span>For sectioned workflows, RegBridge recommends a worksheet and field mapping for every section.</span></li><li><strong>Review recommendations.</strong><span>Verify exact and approved-alias matches; mark optional sections with no transactions.</span></li><li><strong>Run preflight.</strong><span>Clear blocking findings and review all advisory findings across the bundle.</span></li><li><strong>Generate and inspect.</strong><span>Download the regulator workbook, review it, and submit it yourself.</span></li></ol><button className="button button--primary" type="button" onClick={onStart}>Start preparing a return</button></section>
        <section className="help-card"><p className="eyebrow">Current limits</p><h2>Local import controls</h2>{limits ? <dl className="limits-list"><div><dt>Maximum file</dt><dd>{formatMegabytes(limits.max_file_size_bytes)}</dd></div><div><dt>Maximum rows</dt><dd>{limits.max_rows.toLocaleString()}</dd></div><div><dt>Maximum columns</dt><dd>{limits.max_columns.toLocaleString()}</dd></div><div><dt>XLSX worksheets</dt><dd>{limits.max_xlsx_sheets}</dd></div><div><dt>Preview rows</dt><dd>{limits.preview_rows}</dd></div></dl> : <p className="muted">Limits will appear when the API is connected.</p>}</section>
        <section className="help-card help-card--wide"><p className="eyebrow">Privacy &amp; responsibility</p><h2>What RegBridge retains</h2><div className="boundary-grid"><div><strong>Metadata, not source rows</strong><span>Runs, section mappings, counts, fingerprints, and audit metadata persist in PostgreSQL.</span></div><div><strong>Runtime values stay transient</strong><span>Personal declaration and period values must be re-entered when a run is resumed.</span></div><div><strong>Organisation-isolated access</strong><span>Authenticated production sessions operate only within the selected organisation and assigned OWNER or MEMBER role.</span></div><div><strong>No AI decisions</strong><span>Worksheet selection, mappings, saved-profile matching, and regulatory checks are deterministic.</span></div><div><strong>No workbook archive</strong><span>Generated bytes remain transient; artifact fingerprints and audit history remain available.</span></div></div></section>
      </div>
    </div>
  )
}
